export {default as About} from './about/About'
export {default as Footer} from './footer/Footer'
export {default as Header} from './header/Header'
export {default as History} from './history/History'
export {default as Team} from './team/Team'
export {default as Testimonials} from './testimonials/Testimonials'
